add wave -position end  sim:/test/DMYRD/HRESETN
add wave -position end  sim:/test/DMYRD/HCLK
add wave -position end  sim:/test/DMYRD/HADDR
add wave -position end  sim:/test/DMYRD/HTRANS
add wave -position end  sim:/test/DMYRD/HWRITE
add wave -position end  sim:/test/DMYRD/HSIZE
add wave -position end  sim:/test/DMYRD/HBURST
add wave -position end  sim:/test/DMYRD/HWDATA
add wave -position end  sim:/test/DMYRD/HRDATA
add wave -position end  sim:/test/DMYRD/HREADY
add wave -position end  sim:/test/DMYRD/HRESP
add wave -position end  sim:/test/DMYRD/ISYNC
add wave -position end  sim:/test/DMYRD/OSYNC
add wave -position end  sim:/test/DMYRD/IADR_SIZE
add wave -position end  sim:/test/DMYRD/ISTART
add wave -position end  sim:/test/DMYRD/ISYNC_OFF
add wave -position end  sim:/test/DMYRD/OMON_CNT0
add wave -position end  sim:/test/DMYRD/OMON_CNT1
add wave -position end  sim:/test/DMYRD/HRDAYA_hold
run 10ms;
